### ISSUE TITLE
Getting unauthorized (401) while trying to get EmbedUrl

### ISSUE THREAD

**Issue by RupenAnjaria** [KotanaSai21/powerbi-embedded-React-demo#2]
Getting 401 (unauthorized) error when trying to call for embeded url:
```
    var embedUrl =
        await powerBiClient.GetAsync($"https://{powerBI_API_URL}/v1.0/myorg/groups/{groupId}/reports/{reportId}")
        .ContinueWith<string>((response) =>
        {
            log.LogInformation(response.Result.StatusCode.ToString());
            log.LogInformation(response.Result.ReasonPhrase.ToString());
            PowerBiReport report =
                JsonConvert.DeserializeObject<PowerBiReport>(response.Result.Content.ReadAsStringAsync().Result);
            return report?.EmbedUrl;
        });
```
I am getting the token, however above code isn't working for me. Any suggestion? Will the URL contain "myorg" as it is?

Thank you.

**Comment by KotanaSai21** [comment]
@RupenAnjaria , 

To get the Embed URL for the report, we need to hit the [Get Report in Group  ](https://learn.microsoft.com/rest/api/power-bi/reports/get-report-in-group) or[ Get Report](https://learn.microsoft.com/rest/api/power-bi/reports/get-report) REST APIs.

Refer[ Troubleshoot documentation](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-troubleshoot). 
Please feel free to reach if still facing any issues

**Comment by RupenAnjaria** [comment]
Yes, I am consuming those URLs however, they require bearer token for authentication. Please see below Postman setup to get token:

![image](https://github.com/KotanaSai21/powerbi-embedded-React-demo/assets/17281745/1b9ed2c9-aa57-479b-9895-3740b6a2b019)

However, consuming API to get EmbededURL returns 401. See setup below where I am using the token from above endpoint:

![image](https://github.com/KotanaSai21/powerbi-embedded-React-demo/assets/17281745/264723a1-c73f-4ee8-a306-3dba5c53cac6)

I checked the troubleshooting document, but it doesn't give any specific info. We also have another page to test the API:
https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-reports-in-group#code-try-0

See on the right side, after we authenticate, it brings a bearer token. If I use that token then it works fine. Not sure from where does that page brings token.
![image](https://github.com/KotanaSai21/powerbi-embedded-React-demo/assets/17281745/e1367510-30a8-4b1b-b83b-4db86f47cdc5)

Does the scope matters when we try to get the bearer token?

**Comment by KotanaSai21** [comment]
Provided in the README file how to setup application and enable service principal to workspace. please follow the steps and give a shot again.

Already Addressed the issue in this [SO Ticket ](https://stackoverflow.com/questions/77796971/getting-bearer-access-token-for-powerbi/77797476#77797476)and [GitHub issue.](https://github.com/microsoft/powerbi-client-angular/issues/50) 

Let me know if you have question.
